"use client";

import ReactMarkdown from "react-markdown";

export default function TermsOfServicepage() {
  return (
    <div className="h-screen w-screen justify-center flex">
      <div className="flex flex-col w-full max-w-[800px] py-24 gap-2">
        <ReactMarkdown className={"gap-6 flex flex-col"}>{`**Terms of Service**

Effective Date: Jan 12th, 2024

Welcome to Yo (Yo..our AI). By using our app and services, you agree to the following terms and conditions. Please read them carefully.

1. Acceptance of Terms By accessing and using Yo, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our app.

2. Use of the Service

Eligibility: You must be at least 13 years old to use our app.
Account: You are responsible for maintaining the confidentiality of your account and password and for all activities that occur under your account.
Compliance: You agree to use the app in compliance with all applicable laws and regulations.
3. AI Interactions Yo provides access to various large language models (LLMs) from different providers. The responses and interactions generated by these AI models are for general purposes and should not be considered as professional advice of any kind.

4. Data Storage We store your chat histories and interactions in our database. While we implement security measures to protect your data, you acknowledge and agree that no method of transmission over the internet is 100% secure. Your use of the service is at your own risk.

5. Limitation of Liability Yo is provided "as is" without warranties of any kind, either express or implied. We are not responsible for any loss or damage resulting from your use of the app, including but not limited to, loss of data or any consequences of AI-generated responses.

6. User Content By using Yo, you retain ownership of your conversation content, but grant us a worldwide, non-exclusive, royalty-free license to store, process, and analyze your conversations for service improvement and functionality purposes.

7. Termination We reserve the right to terminate or suspend your access to Yo at our discretion, without notice, for conduct that we believe violates these Terms of Service or is harmful to other users or our business.

8. Changes to the Terms We may update these Terms of Service from time to time. We will notify you of any changes by updating the date at the top of this page. Your continued use of the app after changes to the terms constitutes acceptance of the new terms.

9. Third-Party Services Our service integrates AI models from various providers (including but not limited to Google, Meta, OpenAI). Each underlying AI model is subject to its provider's terms, and we are not responsible for third-party service interruptions or changes.

10. Contact Us If you have any questions about these Terms of Service, please contact us at demattosanthony@gmail.com.`}</ReactMarkdown>
      </div>
    </div>
  );
}
